apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: karrlein-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karrlein-api
  template:
    metadata:
      labels:
        app: karrlein-api
    spec:
      containers:
      - name: karrlein-api
        image: karrlein/karrlein-api:0.2
---
apiVersion: v1
kind: Service
metadata:
  name: karrlein-api-service
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: karrlein-api
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: karrlein-api-ingress
spec:
  entrypoints:
      - web
  routes:
      - match: Host(`api.karrlein.com`)
        #middlewares:
        #- name: https-redirect
        kind: Rule
        services:
            - name: karrlein-api-service
              port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: karrlein-api-ingress-tls
spec:
  entrypoints:
      - websecure
  routes:
      - match: Host(`api.karrlein.com`)
        kind: Rule
        services:
            - name: karrlein-api-service
              port: 8080
  tls:
      certResolver: karrlein
